### ISSUE TITLE
INTEGER LINEAR PROGRAMMING BASED CODE GENERATION FOR EXPOSED DATAPATH

### ISSUE THREAD

**Issue by destinityx2** [YaccConstructor/Brahma.FSharp#11]
Взять статью [INTEGER LINEAR PROGRAMMING BASED CODE GENERATION FOR EXPOSED DATAPATH](http://dspace.cc.tut.fi/dpub/bitstream/handle/123456789/22646/aijo.pdf?sequence=1)

В названии фигурирует integer linear programming, но в теле ссыль на [constraint integer programming](http://dl.acm.org/citation.cfm?id=1786721) ([ещё](https://docs.google.com/viewer?url=https%3A%2F%2Fwww.zib.de%2Fberthold%2Fconstraint_integer_programming.pdf)). Надо разобраться, что к чему.

Далее.
- [ ] Ребята говорят, что жутко медленно работает. Надо бы взять и посмотреть, не спасут ли GPU. Например
  - [Linear Optimization with CUDA](http://www.idi.ntnu.no/~elster/master-studs/spampinato/spampinato-linear-prog-gpu-report.pdf)
  - [Recent Advances on GPU Computing in Operations Research](http://projects.laas.fr/NVIDIAacademic/4979b778.pdf)
  - [A GPU Implementation of Parallel Constraint-based Local Search](http://cp2013.a4cp.org/sites/default/files/uploads/trics2013_submission_6.pdf)
  - Если я правильно понял, то у [этого](https://github.com/IainNZ?tab=repositories) товарища когда-то быля открытая реализация (см [последний ответ](https://www.or-exchange.org/questions/312/gpu-and-mip-solvers)).
- [ ] Внимательно посмотреть на математику из статьи, на наш граф, на идеи из Reduceron-а, на абстрактную интерпертацию, суперкомпиляцию и прочие частичные вычисления и подумать, нельзя ли что-то улучшить. Например, оптимальность решения задачи распеделения ресурсов как критерий остановки какого-нибудь процесса частичных вычислений.

**Comment by gsvgit** [comment]
Obsolete
