### ISSUE TITLE
LocalMemSize

### ISSUE THREAD

**Issue by kirillgarbar** [YaccConstructor/Brahma.FSharp#145]
Some algorithms require to compute the correct amount of local memory, so adding LocalMemSize member to ClDevice can be helpfull

**Comment by gsvgit** [comment]
@kirillgarbar can you add a link to your implementation of this functionality?

**Comment by kirillgarbar** [comment]
https://github.com/kirillgarbar/GraphBLAS-sharp/blob/58e8a388008587dffda805e645b0cdbddb06c9d4/src/GraphBLAS-sharp.Backend/Common/Utils.fs#L29

**Comment by gsvgit** [comment]
Added in [v2.0.4](https://www.nuget.org/packages/Brahma.FSharp/)
