### ISSUE TITLE
HMM on GPGPU

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Brahma.FSharp#16]
- [x] Реализовать алгоритм [Viterbi](https://en.wikipedia.org/wiki/Viterbi_algorithm) на GPGPU с помощью Brahma.FSharp.
   - [x] Реализовать алгоритм Viterbi на F#. Последовательная версия. 
   - [x] Реализовать алгоритм Viterbi на F#. Параллельная версия.
   - [x] Перенести на GPGPU
- [x] Для тестов и сравнения использовать [HMMer](https://sites.google.com/site/rnainformatics/rna-homology-exercises/exercise-2/howto-hmmer)

**Comment by KochetovKirill** [comment]
Я беру эту
