### ISSUE TITLE
Библиотек функций для работы с массивами на GPGPU

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Brahma.FSharp#17]
Реализовать библиотеку, предоставляющую следующие функции для работы с массивами на GPGPU. Предусмотреть управление копированием данных: при последовательном выполнении функций на GPU не должно быть лишних копирований с хоста на GPU и обратно.
- [ ] '(!1!)' iter + тесты
- [ ] '(!1!)' iteri + тесты
- [ ] '(!2!)' map + тесты
- [ ] '(!2!)' mapi + тесты
- [ ] '(!2!)' map2 + тесты
- [ ] '(!2!)' reverse + тесты
- [ ] '(!3!)' Тесты на композиции реализованных функций. Проверка правильного управления памятью.
- [ ] Сравнение производительности реализованных функций, функций Array и Array.Parallel

**Comment by LuninaPolina** [comment]
я эту беру
