### ISSUE TITLE
Примеры.

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Brahma.FSharp#19]
- [x] '(!1!)' Исправить [багу](https://github.com/gsvgit/Brahma.FSharp/issues/46)
- [ ] Создать примеры использования Brahma.FSharp в виде отдельного проекта.
  - [x] Код. На каждый случай придумать и реализовать 3-4 различные задачи.
    - [x] '(!2!)' Матрицы
    - [x] '(!2!)' Массивы
    - [x] '(!2!)' Арифметика с плавающей точкой
    - [x] '(!3!)'Агенты
  - [ ] Документация к примерам на http://yaccconstructor.github.io/Brahma.FSharp/

**Comment by SokolovEgor** [comment]
Возьму эту задачу
