### ISSUE TITLE
BIO: CYK + CM on GPGPU for graph input

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Brahma.FSharp#20]
- [ ] Реализовать алгоритм CYK на GPGPU. Можно сразу считать, что грамматика в нормальной форме Хомского.
    - [ ] Реализовать CYK на F#. Простая последовательная реализация. 
    - [ ] Реализовать CYK на F#. Параллельная реализация.
    - [ ] Перенести реализацию на GPGPU
- [ ] Применить CYK для поиска подстроки в строке. 
     -  [ ] Для этого потребуется представить таблицу в виде набора колонок. При смещении вдоль исходной строки можно перевычислять только диагональ. Необходимо обратить внимание на то, что стартовый нетерминал может оказаться не в верхней строке, а ниже.
- [ ] Реализовать тесты производительности

**Comment by SusaninaJulia** [comment]
Я выбрала эту
