### ISSUE TITLE
Обработка транслятором функций типа void

### ISSUE THREAD

**Issue by LuninaPolina** [YaccConstructor/Brahma.FSharp#26]
Проблема: невозможность обработки транслятором функций типа void.
При попытке передачи на компиляцию методу ComputeProvider.Compile цитированной функции, имеющей тип Expr<_ - >unit>, возникает исключение:
System.Exception : Printer. Unsupported statement: Brahma.FSharp.OpenCL.AST.Const`1[Brahma.FSharp.OpenCL.Translator.Common+Lang]
Пример кода:

```
let Iter func (inArr: int array) = 
    let platformName = "*"
    let localWorkSize = 100
    let deviceType = DeviceType.Default
    let length = inArr.Length
    let provider = 
        try ComputeProvider.Create(platformName, deviceType)
        with
        | ex -> failwith ex.Message
    let mutable commandQueue = new CommandQueue(provider, provider.Devices |> Seq.head)
    let command = 
        <@
            fun (rng: _1D) (a: array<_>) ->
                let r = rng.GlobalID0            
                (%func) a.[r]               
        @>
    let kernel, kernelPrepare, kernelRun = provider.Compile command
    let d = new _1D(length, localWorkSize)
    kernelPrepare d inArr
    let _ = commandQueue.Add(kernelRun()).Finish()
    commandQueue.Dispose()
    provider.Dispose()
    provider.CloseAllBuffers()
let arr = [|for i in 1..1000 -> i|]
Iter <@ fun x -> () @> arr
```

**Comment by gsvgit** [comment]
@LuninaPolina Приведите пример кода, пожалуйста.

**Comment by LuninaPolina** [comment]
let Iter func (inArr: int array) = 
    let platformName = "*"
    let localWorkSize = 100
    let deviceType = DeviceType.Default
    let length = inArr.Length
    let provider = 
        try ComputeProvider.Create(platformName, deviceType)
        with
        | ex -> failwith ex.Message
    let mutable commandQueue = new CommandQueue(provider, provider.Devices |> Seq.head)
    let command = 
        <@
            fun (rng: _1D) (a: array<_>) ->
                let r = rng.GlobalID0            
                (%func) a.[r]               
        @>

    let kernel, kernelPrepare, kernelRun = provider.Compile command
    let d = new _1D(length, localWorkSize)
    kernelPrepare d inArr
    let _ = commandQueue.Add(kernelRun()).Finish()
    commandQueue.Dispose()
    provider.Dispose()
    provider.CloseAllBuffers()
let arr = [|for i in 1..1000 -> i|]
Iter <@ fun x -> () @> arr

**Comment by LuninaPolina** [comment]
`let Iter func (inArr: int array) = 
    let platformName = "*"
    let localWorkSize = 100
    let deviceType = DeviceType.Default
    let length = inArr.Length
    let provider = 
        try ComputeProvider.Create(platformName, deviceType)
        with
        | ex -> failwith ex.Message
    let mutable commandQueue = new CommandQueue(provider, provider.Devices |> Seq.head)
    let command = 
        <@
            fun (rng: _1D) (a: array<_>) ->
                let r = rng.GlobalID0            
                (%func) a.[r]               
        @>

    let kernel, kernelPrepare, kernelRun = provider.Compile command
    let d = new _1D(length, localWorkSize)
    kernelPrepare d inArr
    let _ = commandQueue.Add(kernelRun()).Finish()
    commandQueue.Dispose()
    provider.Dispose()
    provider.CloseAllBuffers()
let arr = [|for i in 1..1000 -> i|]
Iter <@fun x -> ()@> arr`

**Comment by LuninaPolina** [comment]
let Iter func (inArr: int array) = 
    let platformName = "*"
    let localWorkSize = 100
    let deviceType = DeviceType.Default
    let length = inArr.Length
    let provider = 
        try ComputeProvider.Create(platformName, deviceType)
        with
        | ex -> failwith ex.Message
    let mutable commandQueue = new CommandQueue(provider, provider.Devices |> Seq.head)
    let command = 
        <@
            fun (rng: _1D) (a: array<_>) ->
                let r = rng.GlobalID0            
                (%func) a.[r]               
        @>
    let kernel, kernelPrepare, kernelRun = provider.Compile command
    let d = new _1D(length, localWorkSize)
    kernelPrepare d inArr
    let _ = commandQueue.Add(kernelRun()).Finish()
    commandQueue.Dispose()
    provider.Dispose()
    provider.CloseAllBuffers()
let arr = [|for i in 1..1000 -> i|]
Iter <@fun x -> ()@> arr

**Comment by LuninaPolina** [comment]
let Iter func (inArr: int array) = 
&nbsp;&nbsp;&nbsp;&nbsp;let platformName = "*"
&nbsp;&nbsp;&nbsp;&nbsp;let localWorkSize = 100
&nbsp;&nbsp;&nbsp;&nbsp;let deviceType = DeviceType.Default
&nbsp;&nbsp;&nbsp;&nbsp;let length = inArr.Length
&nbsp;&nbsp;&nbsp;&nbsp;let provider = 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try ComputeProvider.Create(platformName, deviceType)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| ex -> failwith ex.Message
&nbsp;&nbsp;&nbsp;&nbsp;let mutable commandQueue = new CommandQueue(provider, provider.Devices |> Seq.head)
&nbsp;&nbsp;&nbsp;&nbsp;let command = 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<@
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fun (rng: _1D) (a: array<_>) ->
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;let r = rng.GlobalID0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(%func) a.[r]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@>
&nbsp;&nbsp;&nbsp;&nbsp;let kernel, kernelPrepare, kernelRun = provider.Compile command
&nbsp;&nbsp;&nbsp;&nbsp;let d = new _1D(length, localWorkSize)
&nbsp;&nbsp;&nbsp;&nbsp;kernelPrepare d inArr
&nbsp;&nbsp;&nbsp;&nbsp;let _ = commandQueue.Add(kernelRun()).Finish()
&nbsp;&nbsp;&nbsp;&nbsp;commandQueue.Dispose()
&nbsp;&nbsp;&nbsp;&nbsp;provider.Dispose()
&nbsp;&nbsp;&nbsp;&nbsp;provider.CloseAllBuffers()
let arr = [|for i in 1..1000 -> i|]
Iter <@ fun x -> () @> arr
