### ISSUE TITLE
F# to VSFG

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Brahma.FSharp#3]
Create translator to VSFG for subset of F# language. Language constructions which should be supported.
- [x] let
- [x] let rec
- [x] if-then-else
- [x] nested let-bindings
- [x] basic int arithmetic operations: +, -, * , /
- [ ] basic logical operations: and, or, not
- [x] comparators: <, > , =, <=, >=, <>

**Comment by Mikhail-M** [comment]
we must take into account existing constraints on the parameters of functions
Example:
let f x y - incorrect
let f (x:int) (y:int) - correct

**Comment by Mikhail-M** [comment]
Result of my module is one VSFG.
How we can getting it? Very simple

Example:
input: "
let f (x:int) (y:int) = x + y
let g (x:int) = f 2 g
g 2
"
For every function we match NestedVSFG and added main function who including all previusly/
Obviously, the resulting VSFG for current example is a Call g with nested VSFG "g" and "f"
PS: Resulting VSFG have not input port!

So we can modify out input following: 
"let main = 
let f (x:int) (y:int) = x + y
...
g 2
"
