### ISSUE TITLE
Technical report F#->VSFG->TTA

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Brahma.FSharp#6]
@Mikhail-M , @lares77 , @destinityx2, @kajigor 
We should aggregate all our experience in one doc.

**Comment by Mikhail-M** [comment]
В техе?

**Comment by gsvgit** [comment]
Лучше в гуглодоках. В папке со всеми материалами, что я шарил.

**Comment by gsvgit** [comment]
@kajigor @Mikhail-M @lares77 @destinityx2 Сочинять здесь:  https://docs.google.com/document/d/1caHfh4MqTFNsGrX2AX6i1DK6Fwd7eVMIezMX8vE2LpM/edit
