### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Brahma.FSharp#65]
Create and publish documentation and examples for
- [x] http://fsharp.org/use/gpu/
- [x] http://yaccconstructor.github.io/Brahma.FSharp/
- [x] fix #56 

Can be based on 
- src/UsageExamples

- [x] Create separated repo with examples.
   - [x] Scaffold
   - [x] .NET build
   - [x] Mono build
   - [x] Documentation
- [x] Cleanup main repo

**Comment by SusaninaJulia** [comment]
я беру эту
