### ISSUE TITLE
Workflow builder for array function

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Brahma.FSharp#67]
It is necessary to share gpu context between some array functions (to share arrays). Also it is necessary to manipulate array location (host or GPGPU memory). For inspiration: [cuda workflow](http://quantalea.com/static/app/manual/compilation-workflow-based_gpu_coding.html) 

Workflow should be implemented as separated generic mechanism for GPGPU code template creation. Arrays are just for evaluation.

Documentation on [F# workflow builders](https://fsharpforfunandprofit.com/series/computation-expressions.html)

**Comment by VaseninaAnna** [comment]
Беру эту
