### ISSUE TITLE
Sparse boolean matrix multiplication

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Brahma.FSharp#69]
Implement sparse boolean matrix multiplication.
- each cell can be represented as bit (value is 0 or 1)
- boolean matrix can be sparse (for graphs)
- multiplication can be expressed in terms of bitwise operations

Investigate techniques for sparse matrix multiplication on GPGPU ( [Fast sparse matrix multiplication on GPU](http://dl.acm.org/citation.cfm?id=2872604) or [other](https://github.com/YaccConstructor/YaccConstructor/issues/230))

First possible way: store only ids of nonzero cells (per row, per column, both, global, etc...)

Another way:
Possible representation is one of 'classical' sparse matrix representation over chunked (each chunk is byte, int or int64) rows-cells. Data alignment may be necessary (size of matrix should be divisible to byte, int or int64 respectively).

**Comment by VezhninDan** [comment]
беру эту
