### ISSUE TITLE
Spelling error in exception on failing to compile an fsharp quotation.

### ISSUE THREAD

**Issue by vroksjab** [YaccConstructor/Brahma.FSharp#70]
### Description

Spelling error in exception.

### Repro steps

See Brahma.FSharp\src\Brahma.FSharp.OpenCL.Translator\Body.fs(139)
>> "| c -> failwithf "Unsupporte call: %s" c

### Expected behavior

"Unsupported call: ..."

### Actual behavior

"Unsupporte call: ..."

### Known workarounds

None

### Related information 

None

**Comment by gsvgit** [comment]
@vroksjab thank you! Fixed.
