### ISSUE TITLE
_2D LocalID1 isn't properly translated

### ISSUE THREAD

**Issue by vlj** [YaccConstructor/Brahma.FSharp#95]
### Description

Using the nuget package with a (range:_2D) object, using range.LocalID1 is translated to (range) . LocalID1 in OpenCL which triggers a kernel compilation failure.

### Repro steps

1. Download latest Brahma.FSharp from Nuget in a project
2. Write a kernel that access the second local id.

### Expected behavior

range.LocalID1 should be translated to get_local_idx(1)

### Actual behavior

range.LocalID1 is considered as a structure + member

### Related information 

* Windows 10
* .NET Runtime 4.6.1

**Comment by gsvgit** [comment]
@vlj Should be fixed in [v_1.1.4](https://www.nuget.org/packages/Brahma.FSharp/1.1.4) Please, try it out.

**Comment by vlj** [comment]
It works thanks !
