### ISSUE TITLE
Indexing array of constants generate invalid kernel

### ISSUE THREAD

**Issue by vlj** [YaccConstructor/Brahma.FSharp#96]
### Description

When indexing an array of constants the generated opencl code is missing a parenthesis 

### Repro steps
Build the following code :
`

    let provider = ComputeProvider.Create("*", DeviceType.Gpu)
    let mutable commandQueue = new Brahma.OpenCL.CommandQueue(provider, provider.Devices |> Seq.head)

    let gauss x cPI mean sigma =
        let num = exp( - 0.5 * (pown ((x-mean)/sigma) 2) + (pown (mean/sigma) 2))
        let denum = (2.0 * cPI * sigma * sigma)
        sqrt(num / denum)
    let mean = 7.5;
    let sigma = 8.;
    let cPI= 3.14159265358979323846;
    let weights = Array.init 16 (fun x -> float32(gauss (float x) cPI mean sigma))
    let total = Array.fold (+) (float32 0) weights
    let scratch = Array.init (4 * 49) (fun _ -> byte 0)

    let command global_memory_index local_memory_index= <@ fun (range:_2D) (buf:array<byte>) (dst:array<byte>)->
        let i = range.GlobalID0
        let j = range.GlobalID1
        let local_buf = local scratch
        local_buf.[(%local_memory_index) range.LocalID0 range.LocalID1] <- buf.[(%global_memory_index) i j]
        local_buf.[(%local_memory_index) (range.LocalID0 + 16) range.LocalID1] <- buf.[(%global_memory_index) (i + 16) j]
        local_buf.[(%local_memory_index) (range.LocalID0 + 32) range.LocalID1] <- buf.[(%global_memory_index) (i + 32) j]
        barrier ()
        let mutable res = float32 0.
        for k in 0..15 do
            res <- res + weights.[k] * float32 local_buf.[(%local_memory_index) (range.LocalID0 + 16 + k) range.LocalID1]
            done
        dst.[(%global_memory_index) i j] <-  byte (res / total)
    @>

    let stride = img.Width
    let kernel, kernelprepare, kernelrun = provider.Compile (command <@ fun i j -> (i + j * stride) * 3 + 1 @> <@ fun i j -> i * 16 + j @> )
`
### Expected behavior

Code should compile

### Actual behavior

Exception is throw with the message :
```
1:17:5: error: expected ')'
    [k] * (float) local_buf [((((get_local_id (0) + 16) + k) * 16) + get_local_id (1))])) ;} ;
    ^
1:16:4: note: to match this '('
   ({ 0.0621221, 0.06561401, 0.06876289, 0.0715021, 0.07377182, 0.07552127, 0.07671055, 0.0773122, 0.0773122, 0.07671055, 0.07552127, 0.07377182, 0.0715021, 0.06876289, 0.06561401, 0.0621221}
```

### Known workarounds

Passing array as an argument works but there's some optimisation oportunities missed.

### Related information 

* Windows 10 x64
* Nuget binaries
* .NET 4.6.1

**Comment by gsvgit** [comment]
@vlj 
Constant memory processing should be fixed in [v 1.1.5](https://www.nuget.org/packages/Brahma.FSharp/).
Note, that in OpenCL [__local variable can not be initialized](https://www.khronos.org/registry/OpenCL/specs/opencl-2.0-openclc.pdf#page=37), and we are not support complex logic for local arrays initialization. So it may be necessary to add some code to your kernel to be sure that local_buf is initialized by zero (if it is critical. If not, you can omit this code) :
```
...
        if range.LocalID0 = 0 && range.LocalID1 = 0
        then for i in 0.. size - 1 do local_buf.[i] <- byte 0
        barrier ()
...
```

I think, that "possible correct" code may looks like this.
```
   let gauss x cPI mean sigma =
        let num = exp( - 0.5 * (pown ((x-mean)/sigma) 2) + (pown (mean/sigma) 2))
        let denum = (2.0 * cPI * sigma * sigma)
        sqrt(num / denum)
    let mean = 7.5
    let sigma = 8.
    let cPI= 3.14159265358979323846
    let weights = Array.init 16 (fun x -> float32(gauss (float x) cPI mean sigma))
    let total = Array.fold (+) (float32 0) weights
    let size = 4 * 49     

    let command global_memory_index local_memory_index= <@ fun (range:_2D) (buf:array<byte>) (dst:array<byte>)->
        let i = range.GlobalID0
        let j = range.GlobalID1
        let local_buf = local (Array.zeroCreate size)
        //next 3 lines are necessary for initialization of all cells by 0. May be omitted or changed 
        if range.LocalID0 = 0 && range.LocalID1 = 0
        then for i in 0.. size - 1 do local_buf.[i] <- byte 0
        barrier ()
        local_buf.[(%local_memory_index) range.LocalID0 range.LocalID1] <- buf.[(%global_memory_index) i j]
        local_buf.[(%local_memory_index) (range.LocalID0 + 16) range.LocalID1] <- buf.[(%global_memory_index) (i + 16) j]
        local_buf.[(%local_memory_index) (range.LocalID0 + 32) range.LocalID1] <- buf.[(%global_memory_index) (i + 32) j]
        barrier ()
        let mutable res = float32 0.
        for k in 0..15 do
            res <- res + weights.[k] * float32 local_buf.[(%local_memory_index) (range.LocalID0 + 16 + k) range.LocalID1]
            done
        dst.[(%global_memory_index) i j] <-  byte (res / total)
    @>
```

**Comment by vlj** [comment]
Thanks for the fix.

I don't know what Expression can use but is it possible to have "local" take a type parameter and no argument or size for array argument to make clear that it is not initialized ? like "let local_buf = local<byte>(4 * 49)" or "let local_int = local<int> ()".

**Comment by gsvgit** [comment]
@vlj Thank you for proposal. You are right, currently semantic of ```local``` function is very unclear. I'll try to fix it by one of your variants or find a new one.

**Comment by gsvgit** [comment]
@vlj I create the separate issue #97 on ```local``` function semantics. May this issue be closed?

**Comment by vlj** [comment]
Yes I think it’s ok to close the issue then

 

De : Semyon [mailto:notifications@github.com] 
Envoyé : mardi 12 décembre 2017 08:44
À : YaccConstructor/Brahma.FSharp <Brahma.FSharp@noreply.github.com>
Cc : vlj <vljn.ovi@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [YaccConstructor/Brahma.FSharp] Indexing array of constants generate invalid kernel (#96)

 

@vlj <https://github.com/vlj>  I create the separate issue #97 <https://github.com/YaccConstructor/Brahma.FSharp/issues/97>  on local function semantics. May this issue be closed?
